In [1]:
import torch

## Empty Tensor

Uninitialized Tensors

In [16]:
x = torch.empty(1)
x

tensor([5.0395e-37])

In [17]:
x = torch.empty(3)
x

tensor([4.9272e-37, 0.0000e+00, 0.0000e+00])

In [18]:
x = torch.empty(3,4)
x

tensor([[4.8620e-37, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [19]:
x = torch.empty(2,2,4)
x

tensor([[[4.9271e-37, 0.0000e+00, 6.3371e-10, 2.5038e-12],
         [1.6612e-04, 7.9352e+17, 6.6522e-33, 7.1729e+22]],

        [[7.2065e+31, 1.7089e-40, 7.1732e+22, 7.2065e+31],
         [4.5144e+27, 1.8037e+28, 5.5155e-14, 1.6109e-19]]])

## Tensor with random values

In [20]:
x = torch.rand(3,4)
x

tensor([[0.2254, 0.8976, 0.9515, 0.7689],
        [0.5919, 0.0335, 0.2137, 0.7349],
        [0.6313, 0.9043, 0.5548, 0.0994]])

## Zero tensors

In [21]:
x = torch.zeros(4,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## One Tensor

In [22]:
x = torch.ones(4, 5)
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Looking at tensor datatype

In [24]:
x.dtype

torch.float32

In [25]:
type(x)

torch.Tensor

## Tensor with specified dtype

In [27]:
x = torch.empty(4,5,dtype=torch.int)
x

tensor([[  52997040,          0,         51,          0,         -1],
        [         0, 1600681055, 1718185589, 1601008239,  544434464],
        [ 544501614, 1819307369, 1852140901,  543450484,  544370534],
        [1701869940, 1431323424, 1416916553,    6647929, 1065353216]],
       dtype=torch.int32)

## Tensor Size

In [30]:
x = torch.empty(4,5,dtype=torch.int)
x.size()

torch.Size([4, 5])

## Tensor created from Array

In [31]:
x = torch.tensor([1., 5.0])
x

tensor([1., 5.])

# Tensor basic operations

In [32]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1635, 0.3497],
        [0.4850, 0.7347]])
tensor([[0.7908, 0.6378],
        [0.4269, 0.7953]])


### Elementwise addition

In [34]:
z = x + y
z

tensor([[0.9543, 0.9875],
        [0.9119, 1.5300]])

In [35]:
z = torch.add(x, y)
z

tensor([[0.9543, 0.9875],
        [0.9119, 1.5300]])

## Inplace addition

In [37]:
y.add_(x)
y

tensor([[1.1178, 1.3372],
        [1.3969, 2.2646]])

### <span style="color:red;"> *Every function with trailing underscore in pytorch does inplace operation*</span>

## Elementwise subtraction

In [38]:
z = x - y
z = torch.sub(x,y)

In [39]:
z

tensor([[-0.9543, -0.9875],
        [-0.9119, -1.5300]])

## Elementwise multiplication

In [42]:
z = torch.mul(x,y)
z

tensor([[0.1827, 0.4677],
        [0.6776, 1.6637]])

In [43]:
y.mul_(x)
y

tensor([[0.1827, 0.4677],
        [0.6776, 1.6637]])

## Elementwise division

In [47]:
z = x/y
z

tensor([[0.8946, 0.7478],
        [0.7158, 0.4416]])

In [46]:
z = torch.div(x,y)
z

tensor([[0.8946, 0.7478],
        [0.7158, 0.4416]])

## Slicing operations

In [48]:
x = torch.rand(4,5)

In [49]:
x

tensor([[0.5750, 0.8290, 0.4434, 0.0068, 0.8939],
        [0.3926, 0.5228, 0.0646, 0.4587, 0.4081],
        [0.2247, 0.5530, 0.8200, 0.9420, 0.0349],
        [0.3898, 0.0386, 0.5241, 0.4974, 0.3653]])

In [51]:
x[:,1] # all rows but second column

tensor([0.8290, 0.5228, 0.5530, 0.0386])

In [52]:
x[1,:] # all column but second row

tensor([0.3926, 0.5228, 0.0646, 0.4587, 0.4081])

In [54]:
x[:,2] # all row but 3rd column

tensor([0.4434, 0.0646, 0.8200, 0.5241])

In [55]:
x[1,1]

tensor(0.5228)

In [56]:
x[1,1].item()

0.5227627754211426

## <span style="color:red;"> *item() will give actual value instead of tensor, when there is only one element*</span>

## Reshaping a tensor

In [58]:
x = torch.rand(4,5)
x

tensor([[0.6518, 0.9995, 0.9742, 0.7622, 0.3791],
        [0.1911, 0.6735, 0.3246, 0.7661, 0.6120],
        [0.4924, 0.6480, 0.8498, 0.5943, 0.8745],
        [0.5080, 0.9089, 0.6917, 0.2982, 0.4748]])

In [59]:
x.view(20)

tensor([0.6518, 0.9995, 0.9742, 0.7622, 0.3791, 0.1911, 0.6735, 0.3246, 0.7661,
        0.6120, 0.4924, 0.6480, 0.8498, 0.5943, 0.8745, 0.5080, 0.9089, 0.6917,
        0.2982, 0.4748])

In [60]:
x.view(-1)

tensor([0.6518, 0.9995, 0.9742, 0.7622, 0.3791, 0.1911, 0.6735, 0.3246, 0.7661,
        0.6120, 0.4924, 0.6480, 0.8498, 0.5943, 0.8745, 0.5080, 0.9089, 0.6917,
        0.2982, 0.4748])

In [61]:
x.view(2,-1)

tensor([[0.6518, 0.9995, 0.9742, 0.7622, 0.3791, 0.1911, 0.6735, 0.3246, 0.7661,
         0.6120],
        [0.4924, 0.6480, 0.8498, 0.5943, 0.8745, 0.5080, 0.9089, 0.6917, 0.2982,
         0.4748]])

## <span style="color:red;"> Size will be determined by pytorch if -1 is given in view </span>

In [62]:
x.view(-1)

tensor([0.6518, 0.9995, 0.9742, 0.7622, 0.3791, 0.1911, 0.6735, 0.3246, 0.7661,
        0.6120, 0.4924, 0.6480, 0.8498, 0.5943, 0.8745, 0.5080, 0.9089, 0.6917,
        0.2982, 0.4748])

## Convert tensor to numpy array

In [63]:
import numpy as np

In [65]:
a = torch.rand(2,3)
a

tensor([[0.5079, 0.4838, 0.1270],
        [0.6164, 0.0787, 0.5799]])

In [68]:
b = a.numpy()
b

array([[0.5079347 , 0.48377353, 0.12695432],
       [0.6164197 , 0.0787155 , 0.5799384 ]], dtype=float32)

># <span style="color:red;"> _**Warning**_ </span>
>## _<span style="color:red;"> numpy and tensor share same memory location </span>_

## Converting numpy array to tensor

In [75]:
a = np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
b = torch.from_numpy(a)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

## Creating tensor in cuda

In [79]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z.to('cpu')

>## <span style="color:red;">Converting is not possible at GPU </span>

## Gradient required

In [83]:
x = torch.rand(4,5,requires_grad=True) ## by default it is false, it tells we need to calc grad later
x

tensor([[0.3025, 0.8665, 0.0266, 0.1610, 0.6325],
        [0.8287, 0.9400, 0.5209, 0.1518, 0.4828],
        [0.4841, 0.3332, 0.9461, 0.6069, 0.3317],
        [0.6341, 0.0647, 0.9442, 0.0355, 0.7744]], requires_grad=True)