In [1]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [5]:
y.grad_fn

In [7]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


### ```.requires_grad_()``` function changes ```requires_grad``` property

In [8]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))

In [9]:
a.requires_grad

False

In [10]:
a.requires_grad_(True)

tensor([[-4.8136,  1.0746],
        [ 0.9155, -3.2536]], requires_grad=True)

In [11]:
a.requires_grad

True

In [12]:
b = (a*a).sum()

In [13]:
b.grad_fn

### Gradient Calc

In [15]:
out.backward()

In [16]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

>## ```.backward()``` function can be called only if output is scalar

In [17]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1710.1179, -910.5098,  458.3074], grad_fn=<MulBackward0>)


In [18]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


### Stop autograd tracking history

In [20]:
x.requires_grad

True

In [23]:
(x**2).requires_grad

True

In [27]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [30]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(1, dtype=torch.uint8)
