In [36]:
import torch
import numpy as np

# Uninitislised matrix

In [4]:
x = torch.empty(5,2)
x

tensor([[2.3241e-37, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [7.2149e+22, 1.5975e-43],
        [0.0000e+00, 0.0000e+00],
        [6.7262e-44, 0.0000e+00]])

# Random matrix

In [6]:
x = torch.rand(5,3)
x

tensor([[0.7353, 0.8811, 0.2392],
        [0.1005, 0.0707, 0.6369],
        [0.9372, 0.8186, 0.5427],
        [0.2365, 0.9815, 0.9711],
        [0.9986, 0.5096, 0.2864]])

# Zero matrix with dtype long

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

> From data

In [8]:
x = torch.tensor([5.4, 5])
x

tensor([5.4000, 5.0000])

# Create new based on existing tensor

> ```new_*``` wll take size

> ```*_like``` will make new tensor with same size of input tensor

In [11]:
x = x.new_ones(3,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
x = torch.zeros_like(x)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

>## <span style="color:red;">Other properties can be overriden </span>

In [15]:
x = torch.rand_like(x, dtype=torch.float64)
x

tensor([[0.2279, 0.5275, 0.0509, 0.4047],
        [0.6372, 0.3339, 0.9539, 0.0069],
        [0.1791, 0.9461, 0.5783, 0.3278]], dtype=torch.float64)

# Size

In [16]:
x.size()

torch.Size([3, 4])

# Operations

In [17]:
x = torch.rand(3,3)
y = torch.rand(3,3)

In [18]:
x + y

tensor([[0.2744, 1.1877, 0.7706],
        [0.7177, 1.7549, 1.1124],
        [0.8422, 0.9010, 1.0403]])

In [19]:
torch.add(x,y)

tensor([[0.2744, 1.1877, 0.7706],
        [0.7177, 1.7549, 1.1124],
        [0.8422, 0.9010, 1.0403]])

> Providing output tensor as argument

In [20]:
result = torch.empty(3,3)
torch.add(x,y,out=result)

tensor([[0.2744, 1.1877, 0.7706],
        [0.7177, 1.7549, 1.1124],
        [0.8422, 0.9010, 1.0403]])

# In-place

In [22]:
x.add_(y)

tensor([[0.2744, 1.1877, 0.7706],
        [0.7177, 1.7549, 1.1124],
        [0.8422, 0.9010, 1.0403]])

> <span style="color:red;"> operations postfixed with ```_``` are inplace </span>

# Slice

In [24]:
x[:,1]

tensor([1.1877, 1.7549, 0.9010])

# One-element tensor data

In [25]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.2184])
0.2184157371520996


# Numpy bridge

#### tensor to numpy

In [26]:
a = torch.ones(5)

In [34]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
type(b)

numpy.ndarray

#### numpy to tensor 

In [37]:
a = np.ones(5)

In [38]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)