In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

## Basic autograd

In [2]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [3]:
y = w*x + b

In [4]:
y.backward()

In [5]:
print(x.grad, w.grad, b.grad)

tensor(2.) tensor(1.) tensor(1.)


## Intermediate autograd example

In [9]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [11]:
linear = nn.Linear(3, 2)

In [12]:
linear.weight

Parameter containing:
tensor([[-0.4221, -0.4464, -0.2761],
        [ 0.0476, -0.3313, -0.3354]], requires_grad=True)

In [13]:
linear.bias

Parameter containing:
tensor([-0.3356, -0.2608], requires_grad=True)

In [14]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=.01)

In [15]:
pred = linear(x)

In [18]:
loss = criterion(pred, y)
print(f"loss: {loss.item()}")

loss: 1.0384862422943115


In [19]:
loss.backward()

In [21]:
print(f"dL/dw: {linear.weight.grad}, dL/db: {linear.bias.grad}")

dL/dw: tensor([[-0.6945, -0.1591,  0.1514],
        [ 0.2995, -0.2993, -0.3786]]), dL/db: tensor([-0.1426, -0.4200])


In [22]:
optimizer.step()

In [23]:
pred = linear(x)

In [24]:
loss = criterion(pred, y)
print(f"loss after 1 epoch: {loss.item()}")

loss after 1 epoch: 1.0280550718307495


## Numpy $\leftrightarrow$ Tensor

In [25]:
x = np.array([[1,2],[3,4]])

In [26]:
y = torch.from_numpy(x)

In [27]:
y

tensor([[1, 2],
        [3, 4]])

In [28]:
z = y.numpy()

In [29]:
z

array([[1, 2],
       [3, 4]])

In [30]:
z[0,0] = 1

In [31]:
print(x, y, z)

[[1 2]
 [3 4]] tensor([[1, 2],
        [3, 4]]) [[1 2]
 [3 4]]


## Dataloader()

In [33]:
train_dataset = torchvision.datasets.MNIST(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)


0it [00:00, ?it/s]


 99%|█████████▉| 9838592/9912422 [00:17<00:00, 943137.80it/s]

Extracting ../../data/MNIST/raw/train-images-idx3-ubyte.gz




0it [00:00, ?it/s]



  0%|          | 0/28881 [00:00<?, ?it/s]

 57%|█████▋    | 16384/28881 [00:00<00:00, 88452.30it/s]

32768it [00:00, 36247.06it/s]                           

0it [00:00, ?it/s]

Extracting ../../data/MNIST/raw/train-labels-idx1-ubyte.gz




  0%|          | 0/1648877 [00:00<?, ?it/s]

  1%|          | 16384/1648877 [00:01<00:19, 82170.45it/s]

  3%|▎         | 49152/1648877 [00:01<00:16, 95472.46it/s]

  6%|▌         | 98304/1648877 [00:01<00:12, 121197.35it/s]

 10%|▉         | 163840/1648877 [00:01<00:09, 157737.83it/s]

 13%|█▎        | 212992/1648877 [00:01<00:07, 196344.56it/s]

 22%|██▏       | 368640/1648877 [00:01<00:04, 266008.36it/s]

 27%|██▋       | 442368/1648877 [00:01<00:03, 317100.59it/s]

 31%|███       | 507904/1648877 [00:02<00:04, 239027.81it/s]

 42%|████▏     | 696320/1648877 [00:02<00:02, 322738.12it/s]

 48%|████▊     | 786432/1648877 [00:02<00:02, 390856.85it/s]

 58%|█████▊    | 958464/1648877 [00:02<00:01, 440534.01it/s]

 70%|██████▉   | 1146880/1648877 [00:02<00:00, 527434.26it/s]

 80%|████████  | 1327104/1648877 [00:03<00:00, 668568.23it/s]

 87%|████████▋ | 1441792/1648877 [00:03<00:00, 469841.58it/s]

1654784it [00:03, 473042.97it/s]                             

0it [00:00, ?it/s]

Extracting ../../data/MNIST/raw/t10k-images-idx3-ubyte.gz




  0%|          | 0/4542 [00:00<?, ?it/s]

8192it [00:00, 9251.47it/s]             

Extracting ../../data/MNIST/raw/t10k-labels-idx1-ubyte.gz
Processing...
Done!


In [36]:
image, label = train_dataset[0]

In [37]:
print(image.size(), label)

torch.Size([1, 28, 28]) 5


In [38]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

In [40]:
data_iter = iter(train_loader)

In [41]:
data_iter

In [45]:
image, label = data_iter.next()

In [49]:
label.size()

torch.Size([64])

In [50]:
for image, label in train_loader:
    pass